"""
Sample representations
"""
from pathlib import Path
import pandas as pd

from utils.environments import get_env
from SampleRepresentationConfig import SampleRepresentationConfig

mcfg = SampleRepresentationConfig(
    module_name='sample_representation',
    config=config,
    parameters=workflow.source_path('params.tsv'),
    config_params=[
        'methods',
        'sample_key',
        'cell_type_key',
        'use_rep',
        'var_mask',
        'norm_counts',
        'raw_counts',
        'aggregate',
        'min_cells_per_sample',
        'min_cells_per_cell_type',
        'colors',
        'dask',
    ],
    wildcard_names=['method', 'input_type', 'use_rep', 'var_mask'],
    rename_config_params={'methods': 'method'},
    explode_by=['method', 'use_rep', 'var_mask'],
)
paramspace = mcfg.get_paramspace()


module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *

module preprocessing:
    snakefile: "../../preprocessing/rules/rules.smk"
    config: config

module sample_representation:
    snakefile: "rules.smk"
    config: config

include: "rules/prepare.smk"
include: "rules/methods.smk"
include: "rules/plots.smk"


rule plots_all:
    """
    Collect all sample representation plots for all datasets and methods
    """
    input:
        mcfg.get_output_files(rules.plot_distances.output),
        # mcfg.get_output_files(rules.sample_representation_plot_mds.output),
        mcfg.get_output_files(rules.sample_representation_plot_umap.output),
        mcfg.get_output_files(rules.sample_representation_plot_emb.output),
    localrule: True

rule all:
    message:
        """
        Collect all sample representation analyses for all datasets and methods
        """
    input:
        mcfg.get_output_files(rules.prepare.output),
        mcfg.get_output_files(rules.run_method.output),
        rules.plots_all.input,
    default_target: True
    localrule: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
    localrule: True
