"""
Ambient RNA removal
"""
from pathlib import Path

from utils.ModuleConfig import ModuleConfig
from utils.environments import get_env
from utils.misc import get_use_gpu


mcfg = ModuleConfig(
    module_name='ambient_rna',
    config=config,
    config_params=[
        'counts',
        'batch',
        'raw_file',
        'barcode',
        'gene_id_column',
        'methods',
    ],
    rename_config_params={'batch': 'batch_key'},
)
params = mcfg.get_paramspace()

wildcard_constraints:
    dataset=r'[^/]+',
    file_id=r'[^/]+',
    batch=r'[^/]+',

module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *

include: 'rules/ambient_rna.smk'
include: 'rules/cellbender.smk'
include: 'rules/collect.smk'


rule all:
    input:
        mcfg.get_output_files(rules.collect.output),
    default_target: True
    localrule: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
    localrule: True
