"""
Batch variable analysis with PC regression
"""
from pathlib import Path
import pandas as pd

from utils.environments import get_env
from utils.ModuleConfig import ModuleConfig


mcfg = ModuleConfig(
    module_name='batch_analysis',
    config=config,
    config_params=[
        'covariates',
        'permute_covariates',
        'n_permutations',
        'max_threads',
        'sample',
        'na_strings',
        'raw_counts',
        'normalize',
        'highly_variable_genes',
        'pca',
        'pca_plot',
    ],
    dtypes={
        'max_threads': int,
        'n_permutations': int,
    }
)
paramspace = mcfg.get_paramspace()

module preprocessing:
    snakefile: "../../preprocessing/rules/rules.smk"
    config: config

module sample_representation:
    snakefile: "../../sample_representation/rules/rules.smk"
    config: config

module common:
    snakefile: "../common/Snakefile"
    config: config

use rule * from common as common_ *


include: 'rules/prepare.smk'
include: 'rules/pseudobulk.smk'
include: 'rules/batch_pcr.smk'
include: 'rules/theils_u.smk'


rule all:
    input:
        rules.pseudobulk_all.input,
        mcfg.get_output_files(rules.theils_u.output),
        mcfg.get_output_files(rules.batch_pcr_collect.output),
        mcfg.get_output_files(rules.batch_pcr_plot.output),
    default_target: True
    localrule: True


rule dependency_graph:
    input:
        expand(
            rules.common_dependency_graph.input,
            images=mcfg.image_dir,
            target='all'
        )
    localrule: True
